# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=500)),
                ('contents', models.TextField()),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
    ]
